Sprint 3
vaskes79/middle.messenger.praktikum.yandex pull request #106
Opened 2023-02-26 20:45 UTC by vaskes79

2023-02-27 08:36 UTC, evgenygil requested changes

2023-02-27 08:36 UTC, evgenygil commented on src/api/auth/LogoutApi.ts
> +export class LogoutApi extends BaseAPI {
Кажется нет смысла настолько точечно делить уровни API по разным классам, Logout/SignIn/SignUp, иначе получается на каждый метод свой API? Выглядит избыточно, скорее лучше разделить API по более широкому смыслу, например AuthAPI (login/signup/...), ChatAPI (create chat/send msg etc...)

2023-02-27 08:36 UTC, evgenygil commented on src/api/auth/GetUserApi.ts
> +        Store.setState('user', data);
Все таки работа с внутренним стором не относится непосредственно к api, тут кажется нужен какой-то другой уровень приложения, какой-то модель/контроллер слой, который вызывает api, дальше делает какие-то манипуляции с данными для приложения и потом уже отдает его например в верстку

2023-02-27 08:36 UTC, evgenygil commented on src/api/auth/SignInApi.ts
> +      // Router.go(Paths.signIn);
Лучше написать отдельным комментарием почему код закомментирован или удалить, хранить закомментированный код не лучшая практика

2023-02-27 08:36 UTC, evgenygil commented on src/api/auth/index.ts
> +export const auth = {
Вот как раз auth может быть классом в который можно поместить все методы касающиеся авторизации пользователя, а те внутренние классы отдельные убрать

2023-02-27 08:36 UTC, evgenygil commented on src/api/chats/CreateChatApi.ts
> +export type ChatCreateRes = {
Ничего не имею против такого подхода (типы внутри того же файла), но если что есть еще вариант создавать например файлик `types.ts` рядом и складывать внутрь него, на тот случай если очень много кода будет чуть легче читать, jfyi

2023-02-27 08:36 UTC, evgenygil commented on src/api/messages/MessageSocket.ts
> +      Store.setState('currentWSconnect', this);
Вот здесь тоже, и везде в API у нас пролез слой какой-то логики со стором приложения, API должно вернуть данные, которые другой слой должен обработать

2023-02-27 08:36 UTC, evgenygil commented on src/components/Input/Input.ts
> +  private _detailsShow = false;
Кажется нигде не используется

2023-02-27 08:36 UTC, evgenygil commented on src/core/BaseApi.ts
> +  protected _store: typeof Store;
Стор это не уровень API

2023-02-27 08:36 UTC, evgenygil commented on src/core/HTTPTransport.ts
> +        'Content-type': 'application/json; charset=UTF-8',
Этот заголовок по-моему в каждом методе, может его вынести на уровень выше

2023-02-27 08:36 UTC, evgenygil commented on src/types/Api.d.ts
> +export type User = {
А почему это d.ts? Вообще такие файлы генерит сам ts, мы можем писать их в обычных .ts файлах

2023-02-27 22:03 UTC, vaskes79 commented on src/api/auth/LogoutApi.ts
> +export class LogoutApi extends BaseAPI {
Это драфт, решение. когда будет объём, пойму как это лучше отрефакторить. Оно не красивое, согласен.

2023-02-27 22:05 UTC, vaskes79 commented on src/api/auth/GetUserApi.ts
> +        Store.setState('user', data);
В попыхах решал где иго луче держать, самому показалось это место неудачным, когда закончил, постепенно выпилю из апи лишнее.

2023-02-27 22:05 UTC, vaskes79 commented on src/api/auth/SignInApi.ts
> +      // Router.go(Paths.signIn);
забыл удалить, спасибо, что обратил внимание.

2023-02-27 22:07 UTC, vaskes79 commented on src/api/chats/CreateChatApi.ts
> +export type ChatCreateRes = {
Согласен, лучше разделять, на куски. Если с кодом кто то кроме меня работать будет))), уменьшит колличество конфликтов, чутка.

2023-02-27 22:08 UTC, vaskes79 commented on src/components/Input/Input.ts
> +  private _detailsShow = false;
походу да, спасибо!

2023-02-27 22:14 UTC, vaskes79 commented on src/types/Api.d.ts
> +export type User = {
Изначальня задумка была в том, что бы не импортировать типы как модули а декларировать их в фалах дефенишенов, тогда они становятя видимими на уровне всего приложения, но я не смог настроить ТС конфиг и оставил это на на этап рефактроинга.

2023-02-27 22:21 UTC, vaskes79 commented
@evgenygil Спасибо большое за ревью. Не все смогу реализовать, сейчас, но в процессе планирую допилить. Забыли пароль - это фишка))), поскольку в задании пока не было тасок на реализацию восстановления пароля, оставил так. По поводу сообщений. Не успел их реализовать, работаю над этим, пока только, открываю и закрываю соединение при переключении чатов и заложил ручки для дерганья сообщений, через IntersectionObservers в будующем. Так же не до конца реализована логика редактирирования профиля, но я про все это помню.

2023-03-01 12:11 UTC, evgenygil commented on src/api/messages/MessageSocket.ts
> +  private _eventBuss: EventBus;
Видимо все таки с одной **s** :)

2023-03-01 12:11 UTC, evgenygil commented on src/components/Form/Form.css
> +  height: 101%;
Выглядит как будто немного костыль, возможно проблема не в форме если приходится расширять так ее?

2023-03-01 12:11 UTC, evgenygil commented on src/initHandlers.ts
> +    await API.auth.logout();
А что будет в том случае, если здесь мы "упадем"? можно нужно добавить какую-то обработку исключения

2023-03-06 07:16 UTC, evgenygil commented on src/api/auth/GetUserApi.ts
> +      this._error.error('GetUserApi respoce error');
`response`

2023-03-06 07:16 UTC, evgenygil commented on src/api/auth/SignInApi.ts
> +        this._eventBus.emmit('form:error', reasons);
`emit`

2023-03-06 07:16 UTC, evgenygil commented on src/api/chats/CreateChatApi.ts
> +export type ChatCreateRes = {
Как показывает практика, это вообще один из самых важных пунктов при коммерческой разработке, понятный самодокументированный код, который читаешь и понимаешь что куда идет и где что происходит

2023-03-06 07:16 UTC, evgenygil commented on src/api/chats/GetAllChatsApi.ts
> +    super('/chats?limit=100', baseUrl);
Не критикал, но можно сделать лимит кастомизируемым

2023-03-06 07:16 UTC, evgenygil commented on src/components/Modal/Modal.ts
> +    return true;
Вот это что-то странное, во-первых всегда возвращает true, зачем она тогда? И во-вторых она зачем-то асинхронная?

2023-03-06 07:16 UTC, evgenygil commented on src/core/DateTimeService.ts
> +    msg = `Error: ${msg}` || 'Error: DateTimeService';
Вот так делать не надо, мутируем приходящую в функцию переменную, нужно просто вернуть новую модифицированную

2023-03-06 07:16 UTC, evgenygil commented on src/core/DateTimeService.ts
> +    baseDate = baseDate || new Date();
Опять мутирование входящей переменной, нужно принимать аргументы и на их основе выдавать какой-то результат в новой

2023-03-06 07:16 UTC, evgenygil commented on src/types/Api.d.ts
> +export type User = {
Нет особого смысла в этом (декларации типов глобально), если это не картинка какая-то, и ты для всех определяешь ее, типа *.png или например js библиотека не сопровождаемая типами, конкретные типы твои же лучше хранить рядом с сущностями и в обычных ts

2023-03-06 07:16 UTC, evgenygil commented on src/api/auth/GetUserApi.ts
> +        this._eventBus.emmit('form:error', reasons);
`emit`

2023-03-09 17:35 UTC, merged